<section>
	<p class="doc-kicker">Community</p>
	<h2>Our origin story</h2>
	<p>Over the past two years now, we have been meticulously at work. Working first to understand how we arrived at a digital environment that feels so intrusive, hostile, exhausting, and then, working on something precious, full of life by virtue of serving the life within. Dyad is the product of such care and intention.</p>
	<p>We did not like how being social online felt. The platforms we meet on left little room for our humanity. We are stripped down to a certain version of ourselves, and not the version we wanted to come forth. There was no room for the complexity of our experiences, the intricacy of making sense of them, and with that, discovering and nurturing the meaning of our lives. Where do you go online to expand, deepen, texture?</p>
	<p>A face to face conversation is part of the oral culture we only recently parted ways with. Stories and conversations have so long been how we weave parts of us together. And we wanted to give way to more of them.</p>
	<h3>Where dyad comes from</h3>
	<p>Dyad started as Dare. We designed an ugly duckling version of what we had in mind online and invited people to curated conversations. A topic, a question and four to eight people who wanted to meet for that. Our first users, two hundred of them, have taken something so humble, the private alpha of our product, and turned it into something extraordinary.</p>
	<p>Over a hundred conversations, all across Berlin. We were flooded with people who had felt what we felt to begin with. We connected, conversed, and brought layers to our thinking behind the product.</p>
	<p>Dyad is now in its private beta and opens in Berlin for one-on-one conversations. We have a vision for an ecosystem in service to connection and collective sensemaking that brightens up our eyes every time we zoom out and circle back. That is to say, Dyad, the app to start and surface face to face conversations is only the beginning.</p>
	<h3>Decisions worth voicing</h3>
	<p>Although simple at face value, there is not a single decision that went into the making of Dyad that we have not deliberately thought about. A select few are worth voicing.</p>
	<p>Dyad is a hyper local, curated network. This is among the many decisions we took to bend the overwhelm of the internet. The March 2026 verdicts against Meta and YouTube are the culmination of decades of work on digital rights and privacy and affirm that platform design is intentional and liable to its effects. With that, we situate ourselves within a countermovement to the commodification and surveillance of our social lives.</p>
	<p>How a platform is owned decides what it becomes. Social platforms begin with a niche, do great service, and end up extractive because traditional corporate models cannot keep operational decisions separate from shareholder interests. We are building dyad so that the mission governs the money, not the other way around: participatorily, with the people who use it, and in the open. It is our acts rather than our words that make the difference with such critical considerations.</p>
	<p>Dyad is built on a framework that follows the open and decentralised original intentions of the web. The fact that we do not yet own the data we create online and how little we know and can affect of the collection, archival, and usage of this information is absolutely bonkers. We nest ourselves in the movement towards open, decentralised infrastructure that makes these matters right.</p>
	<p>We feel that in speaking our minds as we build Dyad, we give the most honest insider view into what is happening inside the community. If you feel spoken to, join us still early in the way and let's talk.</p>
	<p>With care and joy,<br>Luna</p>
</section>
