// Test stub for SvelteKit's `$env/static/public` in the integration suite.
// The real module is generated by the SvelteKit build; under vitest we alias to
// this so server modules that import public env (e.g. supabase-admin.ts) load.
// Values come from .env.local (loaded by vitest.config.integration.ts).
export const PUBLIC_SUPABASE_URL = process.env.PUBLIC_SUPABASE_URL ?? '';
export const PUBLIC_SUPABASE_ANON_KEY = process.env.PUBLIC_SUPABASE_ANON_KEY ?? '';
